### ISSUE TITLE
Json error when checking mod update

### ISSUE THREAD

**Issue by thibo1138** [TekkaGB/DivaModManager#10]
Mod updating is failing after a json error
<img width="1099" alt="Capture d’écran 2022-07-24 à 16 16 25" src="https://user-images.githubusercontent.com/20288083/180886048-a5716597-de18-44e4-94e8-fdb9b912e77b.png">

I checked the targeted line but nothing seems wrong:
<img width="1121" alt="Capture d’écran 2022-07-24 à 16 23 21" src="https://user-images.githubusercontent.com/20288083/180886110-cd9dc453-793c-4c4c-8c19-4bf17d337787.png">

An idea of what might cause the error?

**Comment by hiranokite** [comment]
this occurs when some mod had the download removed from GB, you need to find this specific mod and delete "mod.json" to bypass this error.

**Comment by thibo1138** [comment]
Found it : it was a mod called "egg's songpack" the mod was removed but i don't know why exactly

Thanks for the solution
