### ISSUE TITLE
Unable to install new mods

### ISSUE THREAD

**Issue by gently-confused** [TekkaGB/DivaModManager#14]
5 days ago my mod loader refused to install new mods. I've tried every way of installing them (in loader, game banana 1 click install, dragging and dropping files) and nothing works. The error message that comes up is [ The JSON value could not be converted to System.Int64. Path: $[8]._tsDateUpdated | LineNumber: 2221 | BytePositionInLine: 30. ]. I am unsure what to do, any ideas?
![asdads](https://user-images.githubusercontent.com/110678866/183096311-f7d0dc82-d0e7-4ec2-a004-6d9c2294758a.JPG)

**Comment by TekkaGB** [comment]
Not sure what's happening but that error message is unrelated. However, I did fix the error message in v1.2.3

**Comment by gently-confused** [comment]
Well it suddenly started working again and yes I managed to fix what was giving me the error in the new update. Not sure what happened but thank you!
