### ISSUE TITLE
Cannot install certain mods: "Couldn't extract *.7z: Specified method is not supported."

### ISSUE THREAD

**Issue by twisteroidambassador** [TekkaGB/DivaModManager#28]
When trying to install certain mods directly within DMM, the download completes, then an error message is shown:

```
---------------------------
Warning
---------------------------
Couldn't extract mm_futuretonecustomization_v115.7z: Specified method is not supported.
---------------------------
OK   
---------------------------
```

I've found this to happen with these mods:
https://gamebanana.com/mods/382103
https://gamebanana.com/mods/386869
https://gamebanana.com/mods/383478

The common thing about these mods: They are all made by M&M, and have been updated very recently.

**Comment by magnus1500** [comment]
can confirm issue. same mods, same author. Couldn't extract mm_xxxxx.7z specified method not supported

**Comment by Lucien-X** [comment]
Same issue here (^w^)

**Comment by jiut** [comment]
same
