### ISSUE TITLE
[request] DIVA Mod Archive integration

### ISSUE THREAD

**Issue by Caliel666** [TekkaGB/DivaModManager#8]
[website](https://divamodarchive.xyz/) it already has a [API](https://github.com/BroGamer4256/divamodarchive/blob/master/src/api/v1.json) you can use to talk to it

**Comment by BroGamer4256** [comment]
All fully [documented](https://github.com/BroGamer4256/divamodarchive/blob/master/src/api/v1.json) too

**Comment by TekkaGB** [comment]
Added support in release 1.2.0
